Repository jeonbyeongmin/yum, pull requests merged in 2022-06, with the labels that each got.

#14 feat : 레시피 등록 페이지 UI
  json/data.json
  src/components/Ingredient/index.tsx
  src/mock.ts
  src/pages/RegistRecipe.tsx
  src/styles/global-styles.tsx
  src/types/recipe.ts
Labels: UI

#26 #25/store page UI 제작
  src/components/RecipeItem/index.tsx
  src/components/StoreItem/index.tsx
  src/components/StoreItemList/index.tsx
  src/pages/Store.tsx
Labels: 기능 개발, UI

#30 #27/feat recipe regist firebase
  src/api/recipeRegist.ts
  src/components/Header/index.tsx
  src/components/ImageFile/index.tsx
  src/components/ImageFileBox/index.tsx
  src/components/RecipeStep/ImageFileInput.tsx
  src/components/RecipeStep/RecipeStepItem.tsx
  src/components/RecipeStep/index.tsx
  src/firebase.js
  src/pages/RegistRecipe.tsx
  src/types/recipe.ts
Labels: 기능 개발

#35 Feat/#34 auth
  package-lock.json
  package.json
  src/api/auth.ts
  src/components/Header/index.tsx
  src/firebase.js
  src/pages/Login.tsx
  src/pages/Register.tsx
  yarn.lock
Labels: 기능 개발, 환경 설정

#38 style: 스토어 디테일 페이지 구성요소 변경 및 북마크 버튼 추가
  src/components/ProductInfo/index.tsx
Labels: UI

#50 Fix/#47 UI
  src/common/utils/getCommaFormatting.ts
  src/components/BasketItem/index.tsx
  src/components/Counter/index.tsx
  src/components/Header/index.tsx
  src/components/MyInfo/index.tsx
  src/components/MySpinner/index.tsx
  src/components/PopularRecipeList/index.tsx
  src/components/RecipeItem/index.tsx
  src/components/ResultBox/index.tsx
  src/components/StoreItem/index.tsx
  src/components/StoreItemList/index.tsx
  src/pages/Login.tsx
  src/pages/MyPage.tsx
  src/pages/Register.tsx
  src/pages/ShoppingBasket.tsx
  src/pages/index.tsx
Labels: 리팩토링, UI

#55 Feat/#54 connect detail
  src/api/store.ts
  src/components/Header/index.tsx
  src/components/IngredientSelectModal/index.tsx
  src/components/ProductImage/index.tsx
  src/components/RecipeDetail/RecipeDetailStep.tsx
  src/components/RecipeDetail/RecipeInfo.tsx
  src/components/RecipeDetail/StepItem.tsx
  src/components/RecipeItem/index.tsx
  src/components/RecipeItemList/index.tsx
  src/components/StoreItemList/index.tsx
  src/pages/index.tsx
  src/pages/recipe/[id].tsx
  src/pages/recipe/detail.tsx
  src/pages/store.tsx
  src/pages/store/[Id].tsx
  src/pages/store/detail.tsx
Labels: 기능 개발, 리팩토링, UI

#58 landing page 캐로셀 적용
  src/components/RecipeItem/index.tsx
  src/components/RecipeItemList/index.tsx
Labels: 기능 개발, UI
